export enum TestTypeEnum {
    CatchGameEvent = "catch_game_event",
    WaitUntil = "wait_until",
    CheatAction = "cheat",
    CloseHtmlPopup = "close_html_popup",
    ClosePanelMobile = "close_panel_mobile",
    DelayTask = "delay",
    MouseOverAction = "mouseover",
    MouseOutAction = "mouseout",
    OpenHtmlPaytable = "open_html_paytable",
    OpenPanelMobile = "open_panel_mobile",
    PayoutCheckAction = "payout_check",
    PayoutReadAction = "payout_read",
    ReloadAction = "reload",
    ScreenShotAction = "screen_shot",
    ScrollPaytableByStepAction = "scroll_paytable_by_steps",
    TestClickButton = "click",
    ClickAnywhere = "click_anywhere",
    Emit = "emit"
}
